AWSTemplateFormatVersion: '2010-09-09'
Description: 'LambdaForge - No IAM Template (uses existing service role)'

Parameters:
  ProjectName:
    Type: String
    Default: lambdaforge-production
    Description: Name of the project
  Environment:
    Type: String
    Default: Development
    AllowedValues:
      - Development
      - Staging
      - Production
    Description: Environment type

Resources:
  # S3 Bucket - Simple version without custom naming
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-logs'
      RetentionInDays: 14
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  S3BucketName:
    Description: S3 Bucket Name
    Value: !Ref S3Bucket
    Export:
      Name: !Sub '${ProjectName}-s3-bucket'

  LogGroupName:
    Description: CloudWatch Log Group Name
    Value: !Ref LogGroup
    Export:
      Name: !Sub '${ProjectName}-log-group'

  Instructions:
    Description: Next Steps
    Value: 'S3 bucket and CloudWatch log group created successfully. To add Lambda functions, please ensure your AWS user has IAM permissions or contact your AWS administrator.' 